name: CI/CD PayPhone

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Descargar proyecto
      uses: actions/checkout@v4

    - name: Instalar Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Instalar dependencias
      run: npm install

    - name: Revisar sintaxis
      run: node --check server.js

    - name: Proyecto listo
      run: echo "Build completado"